// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmhnF90YIIRKlQNtaOKh2EkAVBmScPTJE',
    appId: '1:308968450612:web:d7a0dd6a32e441efe27861',
    messagingSenderId: '308968450612',
    projectId: 'enfin-libra-fc3b6',
    authDomain: 'enfin-libra-fc3b6.firebaseapp.com',
    storageBucket: 'enfin-libra-fc3b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RbJb_IQQKO6Hta4K3Xtbhj4ZdVSFkHo',
    appId: '1:308968450612:android:286419b4eab6699fe27861',
    messagingSenderId: '308968450612',
    projectId: 'enfin-libra-fc3b6',
    storageBucket: 'enfin-libra-fc3b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGBy_oMRp4ypdmR0Llc6aDL-O3nYsiQuI',
    appId: '1:308968450612:ios:0c7c4f1b9a4d519ee27861',
    messagingSenderId: '308968450612',
    projectId: 'enfin-libra-fc3b6',
    storageBucket: 'enfin-libra-fc3b6.firebasestorage.app',
    iosBundleId: 'com.example.enfinLibre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGBy_oMRp4ypdmR0Llc6aDL-O3nYsiQuI',
    appId: '1:308968450612:ios:0c7c4f1b9a4d519ee27861',
    messagingSenderId: '308968450612',
    projectId: 'enfin-libra-fc3b6',
    storageBucket: 'enfin-libra-fc3b6.firebasestorage.app',
    iosBundleId: 'com.example.enfinLibre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmhnF90YIIRKlQNtaOKh2EkAVBmScPTJE',
    appId: '1:308968450612:web:582f684e469f8e6de27861',
    messagingSenderId: '308968450612',
    projectId: 'enfin-libra-fc3b6',
    authDomain: 'enfin-libra-fc3b6.firebaseapp.com',
    storageBucket: 'enfin-libra-fc3b6.firebasestorage.app',
  );

}